version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: miranda-manager-frontend
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
volumes:
  miranda-manager-volume-frontend: