version: "3"

services:
  app: 
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: miranda-manager-app
    ports:
      - 5000:5000
    volumes:
      - .:/app
volumes:
  miranda-manager-volume:

