version: "3"

services:
  app: 
    build: 
      context: .
      dockerfile: app.dockerfile
    container_name: miranda-manager-app
    ports:
      - 5000:5000
    volumes:
      - miranda-manager-volume:/app
  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    container_name: miranda-manager-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - miranda-manager-volume:/data/db
    networks:
      - miranda-manager-network

  mongo-express:
    build:
      context: .
      dockerfile: mongo-express.dockerfile
    container_name: miranda-manager-mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASIC_AUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
    networks:
      - miranda-manager-network
    depends_on:
      - mongo
volumes:
  miranda-manager-volume:
networks:
  miranda-manager-network:
    driver: bridge

